### ISSUE TITLE
What steps did you take to publish your language server for use in other editors besides Visual Studio Code?

### ISSUE THREAD

**Issue by hamirmahal** [Beaglefoot/awk-language-server#14]
I'm looking to do something similar, and I think I have almost the same setup as you, with `client` and `server` subdirectories, and the VSCode LSP example as a template. I'm not sure how to take the language server I think I have basically living in a `server` subdirectory, and "export", or "publish" that so can we use it with other LSP-compliant editors like Vim.

**Comment by Beaglefoot** [comment]
In this case you need to exchange messages through stdin/stdout and create some kind of CLI for your server. Here's some related code:

https://github.com/Beaglefoot/awk-language-server/blob/master/server/src/server.ts#L32
https://github.com/Beaglefoot/awk-language-server/blob/master/server/src/cli.ts

Please use Discussions instead of Issues for questions like these.

**Comment by hamirmahal** [comment]
Sorry about that. I usually look for the Discussions tab, first, but the repositories I've been looking at relatively recently don't have them, so I got into the habit of going straight to the "Issues" section to ask questions.

I just opened a Discussion for a new topic that's not heavily related to this one.
